### PR TITLE
TLKWebRTC minor updates

### PR DESCRIPTION
**Pull request by piemonte**
hey otalk,

i made a variety of updates for this component. i didn't dig too much into the overall logic. after re-compiling webrtc for 64-bit on a newer revision, there were a couple changes that had to be made in order to build:

https://github.com/piemonte/TLKWebRTC/commit/3a25377f1818e3dfc772dc36f77482531b215738
https://github.com/piemonte/TLKWebRTC/commit/36377099ddb8b115f11dc0f82ef8dd0a2ddbe680

it's okay, if you don't accept these changes, i'm using them on my own, but wanted to share incase there was interest or if you wanted to cherry-pick anything.

take care. :v:

### CODE REVIEW

**Comment by hjon** [comment]
Thanks for the proposed changes! (I'm using this reply as part of https://github.com/otalk/TLKSimpleWebRTC/pull/3 for convenience and completeness.)

Would you be able to split up the changes into smaller pull requests? That's our preferred process and makes it a bit easier to go through than cherry-picking, as well as allowing comments/changes in a more fine-grained manner. If not, I still intend to go through them within a few weeks; it'll just take a bit longer as my attention is elsewhere at the moment.

**Comment by piemonte** [comment]
hey @hjon, thanks for looking at the requests, great libraries. i started out splitting these into smaller chunks but couldn't wait for them to get merged with some time constraints i have.

unfortunately, i can't go back and redo these because of time too. the logic is pretty much the same, most of the changes are for adhering to certain objc conventions and each commit is a single atomic change. hopefully that's cool. :v:

**Comment by hjon** [comment]
Thanks for the patch! Sorry it took so long to get to. Overall it looks good to me, so I'm merging it in. In the interest of "least surprise", I want to mention that the style may change in the future. Some things differ from my usual practice, but since I don't feel too strongly about them, I'd rather accept a consistent approach (at least until I have stronger opinions and document them). :smiley:

**Comment by piemonte** [comment]
:+1:

**Pull request merged**
